#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <arpa/inet.h>
#include <pthread.h>
#include <sys/ioctl.h>
#include <fcntl.h>
#include <sys/epoll.h>
#include <ncurses.h>
#include <signal.h>
#include <locale.h>
#include <sys/time.h>
#include <math.h>
#include <cjson/cJSON.h>

#include "datatype.h"
#include "global.h"
#include "common.h"
#include "color.h"
